### ISSUE TITLE
Error with pwa-elements

### ISSUE THREAD

**Issue by nicobytes** [ionic-team/capacitor-plugin-demo#19]
I try run that demo but fail with ionic serve

![Screen Shot 2019-05-26 at 9 50 36 AM](https://user-images.githubusercontent.com/7611944/58382734-cc8d9500-7f9b-11e9-872e-58942c78d8fb.png)

**Comment by dotNetkow** [comment]
hey there - sorry about that! Needed to update this repo to Capacitor 1.0 and a different PWA Elements import strategy. Please pull latest from master, it should work now.
